command:
  - "gunicorn"
  - "server.app:app"
  - "-c"
  - "gunicorn_conf.py"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"
  - "--timeout"
  - "1800"
env:
  - name: DATABASE_ENV
    value: postgres
