command:
  - "gunicorn"
  - "server.app:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"
  - "--timeout"
  - "1800"

# SQLite Rescue: Backup/restore DB to Unity Catalog Volume for persistence
# across container restarts. Set this to your Volume path, e.g.:
#   /Volumes/<catalog>/<schema>/<volume>/workshop.db
#
# env:
#   - name: SQLITE_VOLUME_BACKUP_PATH
#     value: "/Volumes/your_catalog/your_schema/your_volume/workshop.db"
#   - name: SQLITE_BACKUP_AFTER_OPS
#     value: "50"  # Backup after every 50 write operations (default: 50, 0 to disable)