"""add_assisted_facilitation_v2_tables

Revision ID: 0f8f0efbbe57
Revises: 0010_discovery_findings_category
Create Date: 2026-01-26 11:30:36.824147
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0f8f0efbbe57'
down_revision = '0010_discovery_findings_category'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Assisted Facilitation v2: ClassifiedFindings for LLM-categorized findings
    op.create_table('classified_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workshop_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('promoted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Assisted Facilitation v2: Disagreements table for auto-detected conflicts
    op.create_table('disagreements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workshop_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('user_ids', sa.JSON(), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Assisted Facilitation v2: Trace-level discovery questions (broadcast to all participants)
    op.create_table('trace_discovery_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workshop_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.Column('target_category', sa.String(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Assisted Facilitation v2: Per-trace thresholds for category coverage
    op.create_table('trace_discovery_thresholds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workshop_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Assisted Facilitation v2: Draft rubric staging area (promoted findings)
    op.create_table('draft_rubric_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workshop_id', sa.String(), nullable=False),
    sa.Column('source_finding_id', sa.String(), nullable=False),
    sa.Column('source_trace_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('promoted_by', sa.String(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_finding_id'], ['classified_findings.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft_rubric_items')
    op.drop_table('trace_discovery_thresholds')
    op.drop_table('trace_discovery_questions')
    op.drop_table('disagreements')
    op.drop_table('classified_findings')
    # ### end Alembic commands ###


